<?php

namespace Tests;

use App\Group;
use App\Task;
use App\User;
use Illuminate\Support\Facades\Artisan;
use Laravel\BrowserKitTesting\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    public $baseUrl = 'http://localhost:8000';

    public $user;
    public $group;
    public $task;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = factory(User::class)->create();
        $this->group = factory(Group::class)->create(['user_id' => $this->user->id]);
        $this->task = factory(Task::class)->create(['group_id' => $this->group->id]);
    }

}
